# chats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, ConversationViewSet, MessageViewSet

# Create a DefaultRouter instance
router = DefaultRouter()

include(routers.DefaultRouter())

# Register viewsets with the router
router.register(r'users', UserViewSet, basename='user')
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')

# Define URL patterns
urlpatterns = [
    # Include all URLs generated by the router
    path('', include(router.urls)),
    
    # Add custom endpoints (if any)
    # Note: The 'list_messages' action is already included via the router
]
